In [5]:
# Create a 1D NumPy array of numbers from 10 to 50, step = 5.

import numpy as np

arr = np.arange(10, 51, 5)
print(arr)

[10 15 20 25 30 35 40 45 50]


In [3]:
np.random.rand(3,3)

array([[0.3444834 , 0.99038245, 0.91037924],
       [0.40997917, 0.60390073, 0.83619667],
       [0.38804142, 0.93426235, 0.67723445]])

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.random.randint(0,10,(3,3))

array([[8, 5, 7],
       [6, 4, 4],
       [5, 1, 8]])

In [ ]:
# Given arr = np.arange(25).reshape(5,5), extract the 2nd column.
arr = np.arange(25).reshape(5,5)
arr

col2 = arr[:, 1]   # all rows (:), column index 1 (2nd column)
print(col2)

[ 1  6 11 16 21]


In [10]:
# Replace all odd numbers in an array with -1.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1   # condition: odd numbers
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1]


In [11]:
# Given arr = np.array([3,7,2,9,1]), select all numbers greater than 5.

arr = np.array([3,7,2,9,1])
arr[arr>5]

array([7, 9])

In [12]:
# Extract the sub-matrix from rows 1–3 and columns 2–4 of a 5×5 array.
arr = np.arange(25).reshape(5,5)
arr[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

In [13]:
# Given arr = np.arange(10), reverse the array.
arr = np.arange(10)
print("Original:", arr)

rev = arr[::-1]
print("Reversed:", rev)

Original: [0 1 2 3 4 5 6 7 8 9]
Reversed: [9 8 7 6 5 4 3 2 1 0]


In [14]:
# From arr = np.array([[1,2],[3,4],[5,6]]), get only the second column as a 1D array.
arr = np.array([[1,2],[3,4],[5,6]])
arr[:,1]

array([2, 4, 6])

In [ ]:
# Compute mean, median, variance, and standard deviation of arr = np.array([1,2,3,4,5]).
arr = np.array([1,2,3,4,5])
mean_ = arr.mean()
median_ = np.median(arr)
var_ = arr.var(ddof=0)      # population variance
std_ = arr.std(ddof=0)      # population std

# sample stats (if asked): var_s = arr.var(ddof=1); std_s = arr.std(ddof=1)
mean_, median_, var_, std_

2.0

In [ ]:
x = np.array([3, 7, 1, 9, 5], dtype=float)
x_min, x_max = x.min(), x.max()
x_norm = (x - x_min) / (x_max - x_min)
x_norm

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

dot_prod = a @ b            # or np.dot(a,b) -> 32
elemwise = a * b            # -> array([ 4,10,18])
dot_prod, elemwise

In [ ]:
# Solve the linear system
# 2x + y = 5
# x − y = 1

A = np.array([[2,1],
              [1,-1]], dtype=float)
b = np.array([5,1], dtype=float)

sol = np.linalg.solve(A, b)  # [x, y]
x, y = sol
x, y